export const FETCH_BUSINESSES = "FETCH_BUSINESSES";
export const CREATE_BUSINESS = "CREATE_BUSINESS";
export const SIGN_UP = "SIGN_UP";
export const USER_ACTION_FAILED = "USER_ACTION_FAILED";
export const CREATE_BUSINESS_FAILED = "CREATE_BUSINESS_FAILED";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const LOGIN = "LOGIN";
export const BUSINESS_ACTION_FAILED = "BUSINESS_ACTION_FAILED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SEARCH_BUSINESSES = "SEARCH_BUSINESSES";

